name: Add Issue to Project

on:
  issues:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/add-to-project@v0.5.0
      #  with:
      #    # You can use GITHUB_TOKEN for adding to projects in the same repo
      #    github-token: ${{ secrets.PROJECT_TOKEN }}
      #    project-url: https://github.com/users/Showoffninja/projects/4
      #    # Or use the node ID directly
      #    # project-url: ${{ secrets.PROJECT_ID }}
      
      # Then use your custom action for field population
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Populate project fields
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-id: ${{ secrets.PROJECT_ID }}
          column-name: "Todo"
          custom-field-mappings: |
            {
              "Priority": "field:priority",
              "Size": "field:estimated size",
              "Due Date": "field:due date",
              "Team": "field:team",
              "Area": "field:affected area",
              "Type": "label-contains:bug"
            }
